/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package network_tool_and_pc_comparison;

/**
 *
 * @author Lab-3
 */
public class singlepanel2 extends javax.swing.JPanel {

    /**
     * Creates new form singlepanel2
     */
    public singlepanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(140, 750));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/comp_1.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 70);

        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(30, 170, 80, 30);

        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(30, 270, 90, 30);

        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(30, 380, 90, 30);

        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(30, 470, 90, 30);

        jLabel6.setText("jLabel6");
        add(jLabel6);
        jLabel6.setBounds(30, 560, 100, 30);

        jLabel7.setText("jLabel7");
        add(jLabel7);
        jLabel7.setBounds(30, 640, 90, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
